<div class="fluid">
    <?php
    require_once 'header.phtml';

use OC\Error\Messages;

$msg = new Messages();
    $msg->display();
    ?>
    <div class="tab-pane">

        <table class="table table-striped table-hover" cellspacing="1">
            <thead>
                <tr>
                    <td><strong>Nome</strong></td>
                    <td width="20%" class="text-center"><strong>Titulo</strong></td>
                    <td width="10%" class="text-center"><strong>Texto</strong></td>
                    <td width="10%" class="text-center"><strong>Publicado</strong></td>
                    <td width="10%" class="text-center"><strong>Posição</strong></td>
                    <td width="5%" class="text-center"><strong>Imagens</strong></td>
                    <td width="20%" class="text-center"><strong>Categoria</strong></td>
                    <td width="5%" class="text-center"><strong>Ações</strong></td>
                </tr> 
            </thead>
            <tbody>
                <?php
                foreach ($this->view->readArticle as $article):
                    if ($this->view->url == "/admin/conteudo/category/{$this->view->id}/article" OR $this->view->url == "/admin/conteudo/article"):
                        if ($this->view->id == NULL OR $this->view->id == $article['adm_category']):
                            ?> 
                            <tr>

                                <td><?= $article['adm_name'] ?></td>
                                <td class="text-center"><?= $article['adm_title'] ?></td>
                                <td class="text-center"><?php
                                    if (empty($article['adm_text'])) {
                                        echo "<button class='btn btn-default btn-xs' disabled='disabled'>Sem Texto</button>";
                                    } else {
                                        echo "<button class='btn btn-danger btn-xs' id='button-text' data-id='{$article['id']}'>Ver Texto</button>";
                                    }
                                    ?>
                                </td>
                                <td class="text-center"><?php
                                    if ($article['adm_public'] == 0) {
                                        echo "<a href='/admin/conteudo/article/publicArt/" . $article['id'] . "'><button type='button' class='btn btn-default btn-xs'><i class='glyphicon glyphicon-star-empty'></i></button></a>";
                                    } else {
                                        echo "<a href='/admin/conteudo/article/despublicArt/" . $article['id'] . "'><button type='button' class='btn btn-danger btn-xs'><i class='glyphicon glyphicon-star-empty'></i></button></a>";
                                    }
                                    ?>
                                </td>

                                <td class="text-center"><?= $article['adm_position'] ?></td>
                                <td class="text-center"><?php
                                    if (count($article['adm_images']) <= 0) {
                                        echo "<button class='btn btn-default btn-xs' disabled='disabled'>Sem imagem</button>";
                                    } else {
                                        echo "<button class='btn btn-danger btn-xs' id='button-img' data-id='{$article['id']}'>Ver Imagem</button>";
                                    }
                                    ?>
                                </td>
                                <td class="text-center"><?php
                                    foreach ($this->view->readCategory as $readCat) {
                                        if ($readCat['id'] === $article['adm_category']) {
                                            echo $readCat['adm_name'];
                                        }
                                    }
                                    ?>
                                </td>
                                <td class="text-center">
                                    <a href="/admin/conteudo/article/update/<?= $article['id'] ?>">
                                        <i class="glyphicon glyphicon-cog"></i>
                                    </a>
                                    <a href="/admin/conteudo/article/delete/<?= $article['id'] ?>">
                                        <i class="glyphicon glyphicon-trash"></i>
                                    </a>
                                </td>
                                <?php
                            endif;
                            ?>

                        </tr>
                        <?php
                    endif;
                endforeach;
                ?>
            </tbody>
        </table>
    </div>

</div>

<!-- Modal SELECIONAR IMAGENS -->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modal-img" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="modal-title"></h4>
            </div>
            <div class="modal-body">
                <div class="row">

                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="/admin/js/ajax.js"></script>