<div class="row page-header">
        <div class="col-lg-6">
            <h3>Usuários</h3>
            <ol class="breadcrumb">
                <li><a href="/admin/">Início</a></li>
                <li class="active">Usuários</li>
            </ol>
        </div>
        
        <?php if ($this->view->url == '/admin/user'): ?>
                <a href="/admin/user/form" class="btn btn-success pull-right">
                    <span class="glyphicon glyphicon-plus"></span>
                    Add Categoria
                </a>
            <?php endif; ?>
    
    </div>
    <!-- FIM ROW PAGE-HEADER  -->