<div class="fluid">
    <?php
        require_once 'header.phtml';
        use OC\Error\Messages;
        $msg = new Messages();
        $msg->display();
    ?>
    <div class="tab-pane">


            <table class="table table-striped table-hover" cellspacing="1">
                <thead>
                    <tr>
                        <td><strong>Nome</strong></td>
                        <td class="text-center"><strong>E-mail</strong></td>
                        <td class="text-center"><strong>Login</strong></td>
                        <td class="text-center"><strong>Cadastro</strong></td>
                        <td class="text-center"><strong>Ações</strong></td>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->view->read as $value): ?>
                        <tr>
                            <td><?= $value['adm_name'] ?></td>
                            <td class="text-center"><?= $value['adm_mail'] ?></td>
                            <td class="text-center"><?= $value['adm_login'] ?></td>
                            <td class="text-center"><?= $value['adm_dateCad'] ?></td>
                            <td class="text-center">
                                <a href="/admin/user/update/<?= $value['id'] ?>">
                                    <i class="glyphicon glyphicon-cog"></i>
                                </a>
                                <a href="/admin/user/delete/<?= $value['id'] ?>">
                                    <i class="glyphicon glyphicon-trash"></i>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>

        </div>


</div>