<div class="container">
    <?php require_once 'header.phtml'; ?>
    <?php

    use OC\Error\Messages;

$msg = new Messages();
    $msg->display();
    ?>
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" id="myTab">
        <li class="active"><a href="#users" data-toggle="tab">Usuários</a></li>
        <li><a href="#add" data-toggle="tab">Adicionar</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <!-- LISTANDO USERS -->
        <div class="tab-pane active" id="users">


            <table class="table table-striped table-hover" cellspacing="1">
                <thead>
                    <tr>
                        <td class="text-center"><strong>Nome</strong></td>
                        <td class="text-center"><strong>E-mail</strong></td>
                        <td class="text-center"><strong>Login</strong></td>
                        <td class="text-center"><strong>Cadastro</strong></td>
                        <td class="text-center"><strong>Ações</strong></td>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->view->read as $value): ?>
                        <tr>
                            <td class="text-center"><?= $value['adm_name'] ?></td>
                            <td class="text-center"><?= $value['adm_mail'] ?></td>
                            <td class="text-center"><?= $value['adm_login'] ?></td>
                            <td class="text-center"><?= $value['adm_dateCad'] ?></td>
                            <td class="text-center">
                                <a href="/admin/user/update/<?= $value['id'] ?>">
                                    <i class="glyphicon glyphicon-cog"></i>
                                </a>
                                <a href="/admin/user/delete/<?= $value['id'] ?>">
                                    <i class="glyphicon glyphicon-trash"></i>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>

        </div>
        <!-- ADICIONANDO USERS -->
        <div class="tab-pane" id="add">
            <div class="container">
                <div class="row">

                    <div class="col-lg-8 col-lg-offset-2">

                        <form action="/admin/user/read" method="post" class="form" id="form">
                            <div class="form-group">
                                <label for="nome">Nome Completo</label>
                                <input type="text" id="name" name="name" class="form-control required" placeholder="Ex: João Silva">
                            </div>
                            <div class="form-group">
                                <label for="email">E-mail</label>
                                <input type="text" id="mail" name="mail" class="form-control" placeholder="Ex: joao@site.com">
                            </div>
                            <div class="form-group">
                                <label for="login">Login</label>
                                <input type="text" id="login" name="login" class="form-control" placeholder="Ex: joao">
                            </div>
                            <div class="form-group">
                                <label for="senha">Senha</label>
                                <input type="password" id="pass" name="pass" class="form-control" placeholder="Tente utiliza numeros e caracteres especiais.">
                            </div>
                            <div class="form-group">
                                <label for="repSenha">Repita a Senha</label>
                                <input type="password" id="reppass" name="reppass" class="form-control" placeholder="Digite a mesma senha digitada acima.">
                            </div>
                            <div class="form-group">
                                <input type="hidden" name="action" value="usersadd" />
                                <input type="hidden" name="dateCad" value="<?= date("d/m/Y - H:i:s") ?>" />
                                <button type="submit" class="btn btn-danger">Cadastrar</button>
                            </div>
                        </form>  
                    </div><!-- COL-LS-8 COL-lg-OFFSET-2 -->              
                </div><!-- ROW -->

            </div><!--CONTAINER-->
        </div><!--ID ADD-->
    </div>
</div>  

<?php
$url = new App\Models\Url();
?>
<script type="text/javascript" src="<?php $url->getServer(); ?>/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="<?php $url->getServer(); ?>/js/forms.js"></script>
<script type="text/javascript">

    $('#myTab a').click(function(e) {
        e.preventDefault();
        $(this).tab('show');
    });


</script>
