<div class="fluid">
    <?php
    require_once 'header.phtml';

use OC\Error\Messages;

$msg = new Messages();
    $msg->display();
    ?>

    <div class="row form-img">
        <form action="/admin/conteudo/image/add" method='post' enctype='multipart/form-data'>
            <div class="col-lg-6 col-lg-offset-3">
                <h3>Enviar imagem</h3>
            </div>
            <div class="col-lg-3 col-lg-offset-3">
                <input type='file' name='image[]' class="btn btn-default" multiple/>
            </div>
            <div class="col-lg-2">
                <input type='submit' name='submit' value="Salvar" class="btn btn-danger" />
                <input type='hidden' name='action' value="add" />
            </div>
        </form>     
    </div>

    <div class="row tab-pane margin-top">
        <?php
            $thumb = new OC\Image\Easythumb();

            $read = count($this->view->readImage);
            if ($read <= 0):
                echo '<strong>Nem uma imagem cadastrada</strong>';
            else:
                foreach ($this->view->readImage as $img):
        ?>        
                <div class="col-lg-2">
                    <a href="#" class="thumbnail thumb-height">
                        <img src="../thumbnail.php?thumb=<?= $img['adm_img'] ?>" alt="thumb" />
                    </a>
                    <a href="/admin/conteudo/image/delete/<?= $img['id'] ?>">
                        <i class="glyphicon glyphicon-trash"></i>
                    </a>
                </div>
        <?php
            endforeach;
            endif;
        ?>

    </div>
</div>