<div class="row page-header">
    <div class="col-lg-6">
        <h3>Menu</h3>
        <ol class="breadcrumb">
            <li><a href="/admin/">Início</a></li>
            <li class="active">Menu</li>
        </ol>
    </div>


            <?php if ($this->view->url === '/admin/menu/'.$this->view->id): ?>
    <a href="/admin/menu/form/<?=$this->view->id?>" class="btn btn-success pull pull-right">
                    <span class="glyphicon glyphicon-plus"></span>
                    Novo Item
                </a>
            <?php elseif ($this->view->url === '/admin/menu/category'): ?>
                <a href="/admin/menu/category/form" class="btn btn-success pull-right">
                    <span class="glyphicon glyphicon-plus"></span>
                    Add Categoria
                </a>
                
            <?php endif; ?>


</div>
<!-- FIM ROW PAGE-HEADER  -->