<div class="fluid">
    <?php
        require_once 'header.phtml';
        use OC\Error\Messages;
        $msg = new Messages();
        $msg->display();
    ?>
    <div class="tab-pane">

            <table class="table table-striped table-hover" cellspacing="1">
                <thead>
                    <tr>
                        <td><strong>Nome da Categoria</strong></td>
                        <td width="20%" class="text-center"><strong>Descrição</strong></td>
                        <td width="10%" class="text-center"><strong>Posição</strong></td>
                        <td width="10%" class="text-center"><strong>Itens</strong></td>
                        <td width="10%" class="text-center"><strong>Publico</strong></td>
                        <td width="5%" class="text-center"><strong>Ações</strong></td>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->view->readMenuCat as $menu): ?>
                        <tr>
                            <td><a href="/admin/menu/<?= $menu['id']?>"><?= $menu['adm_name']?> </a></td>
                            <td class="text-center"><?= $menu['adm_description'] ?></td>
                            <td class="text-center"><?= $menu['adm_posicion'] ?></td>
                            <td class="text-center">
                                <span class="badge">
                                    <?php 
                                        foreach ($this->view->readMenu as $m);
                                            if($m['adm_cat'] == $menu['id']){
                                                    echo count($this->view->readMenu);
                                            }else{
                                                echo "0";
                                            }
                                    ?>
                                </span>
                            </td>
                            <td class="text-center">
                                <?php
                                    if($menu['adm_public'] == 0){
                                        echo  "<a href='/admin/menu/category/publicCatMenu/".$menu['id']."'><button type='button' class='btn btn-default btn-xs'><i class='glyphicon glyphicon-star-empty'></i></button></a>";
                                    }
                                    else{
                                        echo "<a href='/admin/menu/category/despublicCatMenu/".$menu['id']."'><button type='button' class='btn btn-danger btn-xs'><i class='glyphicon glyphicon-star-empty'></i></button></a>"; 
                                    }
                                ?>
                            </td>
                            <td class="text-center">
                                <a href="/admin/menu/category/update/<?= $menu['id'] ?>">
                                    <i class="glyphicon glyphicon-cog"></i>
                                </a>
                                <a href="/admin/menu/category/delete/<?= $menu['id'] ?>">
                                    <i class="glyphicon glyphicon-trash"></i>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>

        </div>

</div>